#!/bin/sh
#
# WebTools - Initial download and firewall configuration settings installation for Synology
#
#
# by ChuckPa, a Plex Community member
#
# Ver 1.0 - Initial release
# Ver 1.1 - Processor independence update ('noarch')
# Ver 1.2 - DSM 5.2 & 6.0 (U3) single version compatibility (Syno installer changes) + Upgrade-in-place


# Put error messages in appropriate system log / communicate back to user

WriteLog() {

    touch       "$LOGFILE"
    echo `date -Iseconds` == $*  >> "$LOGFILE"

# Also inform user via Syno package mechanism
    echo `date -Iseconds` == $* >> $SYNOPKG_TEMP_LOGFILE


}

GetHostType() {
 
# define the main flags

HOSTYPE=0

    HOSTTYPE=2   # SYNO
    CURL=/usr/bin/curl
    TAR=/bin/tar
    UNZIP=/usr/syno/bin/unzip
    PKGDIR=/var/packages/WebTools

  return 0

}

GetDestination() {

    # On Synology,  the Pre-install script determines if Plex is present and ok to use ($PMS_DIR)

    PMS_DIR="`synoshare --get Plex | grep Path | awk -F\[ '{ print $2 }' \
                                                   | awk -F\] '{ print $1 }'`"

    WEBTOOLS_DIR="$PKGDIR/target"

  # Now build the Plug-in directory

  PLUGIN_DIR="$PMS_DIR/Library/Application Support/Plex Media Server/Plug-ins"

  # The Logfile (just in case)
  LOGFILE="$PLUGIN_DIR/WebTools.log"

  # Which release.   Release info for WebTools on Github
  RELEASE_LINK="https://api.github.com/repos/dagalufh/WebTools.bundle/releases/latest" 

}

######################################################################
# Get latest release download link, and download that
######################################################################
downloadWT(){
	# Let's start by finding the browser_download_url
	# we will use the tarball directly for now.  (keep both here)

        # That again means, that QNAP'ers using this is not counted :-(
#	DownloadURL=$(/sbin/curl -Lsk $RELEASE_LINK |grep 'browser_download_url')
#       DownloadURL=$(/sbin/curl -Lsk $RELEASE_LINK |grep 'tarball_url')
	DownloadURL="`$CURL -Lsk $RELEASE_LINK |grep 'tarball_url'`"

	# Strip start part of line
	DownloadURL="`echo $DownloadURL | sed -e 's/"tarball_url": "//'`"

	
        # Strip end part of the response
        DownloadURL="`echo $DownloadURL | sed -e 's/..$//'`"


        WriteLog "Webtools completing download and installation" 

#echo DownloadURL = \[$DownloadURL\]

	# Download the darn thingy
	$CURL -Lsk $DownloadURL -o "$PLUGIN_DIR/wt.tar.gz"
	if [ $? -ne 0 ]; then
          WriteLog Error $? while downloading WebTools
          return $? 
        fi

        #WriteLog WebTools download complete

  return 0
}

######################################################################
# Create WT dir if missing, and then extract. remove tarball afterwards
######################################################################
extractWT(){

  if [ $ISUPGRADE ]; then

    WriteLog  "Forcing WebTools upgrade with installer upgrade"

  else

    # Create WebTools.bundle directory
    mkdir -p "$PLUGIN_DIR/WebTools.bundle"
    #WriteLog extractWT: mkdir $PLUGIN_DIR/WebTools.bundle >>  $LOGFILE

    if [ $? -ne 0 ]; then
      WriteLog "ERROR: Could not create WebTools.bundle directory in \' $PLUGIN_DIR '\  \(err $? \) "
      return 1
    fi
  fi

  # Extract WebTools
  $TAR -xf "$PLUGIN_DIR/wt.tar.gz" --overwrite --strip 1 -C "$PLUGIN_DIR/WebTools.bundle"
  if [ $? -ne 0 ]; then
    # unable to extract
    WriteLog "ERROR:  Cannot extract wt.tar.gz to $PLUGIN_DIR/WebTools.bundle \(err $?\)"
    return 1
  fi

  rm -f "$PLUGIN_DIR/wt.tar.gz"
#    $UNZIP -oq "$PLUGIN_DIR/wt.zip" -d "$PLUGIN_DIR/WebTools.bundle"


  # On Synology,  set ownership to plex, not root.
  chown -R plex:users "$PLUGIN_DIR/WebTools.bundle"
  find "$PLUGIN_DIR/WebTools.bundle" -type f -exec chmod 644 {} \;
  find "$PLUGIN_DIR/WebTools.bundle" -type d -exec chmod 755 {} \;

  # Success
  return 0
        
}

#######################################################################

# Get the host type and Destination directories then download and install WebTools into Plex

GetHostType
GetDestination

# Determine if Install or Upgrade
if [ -f "$PLUGIN_DIR/WebTools.bundle/.isloaded" ]; then
  ISUPGRADE=1
fi

# Download (with retry delay (3 sec), max 5 retries) and extract
retries=0
downloaded=0

until [ $retries -gt 5 -a $downloaded -eq 1 ]; do


  downloadWT
  if [ $? -ne 0 ]; then
    retries=`expr $retries + 1`
    WriteLog "ERROR: Cannot download WT from GitHub, sleeping 10 sec. Retry \# $retries"
    sleep 10

  else
    downloaded=1
    break

  fi

done

# Write results in logfile, exit if unable to proceed
if [ $downloaded -eq 0]; then
  WriteLog  "ERROR: Unable to download WebTools after $retries retries.  Installation failure."
  exit 1
fi



# If download was successful,  perform extraction
extractWT  
if [ $? -ne 0 ]; then

  # unable to extract WT and complete installation... ERROR
  WriteLog  ERROR: Could not extract WebTools.  Package installation aborted.
  exit 1
fi


# Mark as loaded
touch "$PLUGIN_DIR/WebTools.bundle/.isloaded"

# Make certain the files in /var/packages are owned by root 
chown -R root:root   /var/packages/WebTools


# If upgrade, force remove firewall descriptions before upgrading
if [ $ISUPGRADE ]; then
  WriteLog INFO:  Removing prior firewall definitions
  /usr/syno/bin/servicetool --remove-configure-file --package WebTools.sc
fi

# Add description of firewall ports to DSM's firewall built-in application list
/usr/syno/bin/servicetool --install-configure-file --package /var/packages/WebTools/target/WebTools.sc

if [ $? -eq 0 ]; then
  WriteLog WebTools firewalls rules definition installed
fi


exit 0
