#!/bin/sh
#
# Uninstall WebTools from DSM
#
# by ChuckPa, a Plex Community member
#
# Ver 1.0 - Initial release
# Ver 1.1 - Make DSM platform independent.  Rely on Plex dependence only
# Ver 1.2 - Update to accomodate DSM 6.0 U3 installer changes


# If there is no Plex, there's nothing to do
synoshare --get Plex
if [ $? -ne 0 ]
then
   exit 0
fi

# Ok, so Plex is still there,  Where is it and let's do our cleanup
PLEX_LIBRARY_PATH="`synoshare --get Plex | grep Path | \
                           awk -F\[ '{ print $2 }' | awk -F\] '{ print $1 }'`"

# remove WebTools from the Plug-ins Dir

## From PR 3-Apr-2016,  Leave Firewall description intact since WebTools.bundle stays
#rm -rf "$PLEX_LIBRARY_PATH/Library/Application Support/Plex Media Server/Plug-ins/WebTools.bundle"

# Remove the ".isrunning" flag (Synology has no further hooks into Webtools)
rm -f "$PLEX_LIBRARY_PATH/Library/Application Support/Plex Media Server/Plug-ins/WebTools.bundle/.isrunning"

# Remove the ".isloaded" flag (Synology thinks WebTools is completely unininstalled)
rm -f "$PLEX_LIBRARY_PATH/Library/Application Support/Plex Media Server/Plug-ins/WebTools.bundle/.isloaded"

# remove the Synology GUI integration link (This is required to avoid a mess)
rm -f /usr/syno/synoman/webman/3rdparty/WebTools

LOG="$PLEX_LIBRARY_PATH/Library/Application Support/Plex Media Server/Plug-ins/WebTools.bundle/WebTools.log"

# Remove the built-in firewall settings
/usr/syno/bin/servicetool --remove-configure-file WebTools.sc
if [ $? -ne 0 ]; then
  echo Warning:  WebTools not automatically removed from Firewall definitions >> "$LOG"
else
 echo WebTools firewall rules successfully removed from Firewall definitions >> "$LOG" 
fi
