#!/bin/sh
# Makespk - Create WTcleaner SPK

# Make the package tar ball first
VER="1.0"

echo ===== making $VER package tarball =====
cd package ; tar cvzf ../package.tgz * ; cd ..

echo ===== making $VER spk =====
tar cvf Synology_Inst-WTcleaner_$VER.spk INFO PACKAGE_ICON.PNG package.tgz scripts

echo ===== moving version $VER spk to bin directory =====
mv Synology_Inst-WTcleaner_$VER.spk ../../bin/synology
